
name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main
jobs:
  deploy_firebase_hosting:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - run: firebase deploy --only hosting
